// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/Makovey/go-keeper/internal/transport/grpc/model"
	gomock "github.com/golang/mock/gomock"
)

// MockServiceStorage is a mock of ServiceStorage interface.
type MockServiceStorage struct {
	ctrl     *gomock.Controller
	recorder *MockServiceStorageMockRecorder
}

// MockServiceStorageMockRecorder is the mock recorder for MockServiceStorage.
type MockServiceStorageMockRecorder struct {
	mock *MockServiceStorage
}

// NewMockServiceStorage creates a new mock instance.
func NewMockServiceStorage(ctrl *gomock.Controller) *MockServiceStorage {
	mock := &MockServiceStorage{ctrl: ctrl}
	mock.recorder = &MockServiceStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceStorage) EXPECT() *MockServiceStorageMockRecorder {
	return m.recorder
}

// DeleteUsersFile mocks base method.
func (m *MockServiceStorage) DeleteUsersFile(ctx context.Context, userID, fileID, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsersFile", ctx, userID, fileID, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUsersFile indicates an expected call of DeleteUsersFile.
func (mr *MockServiceStorageMockRecorder) DeleteUsersFile(ctx, userID, fileID, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsersFile", reflect.TypeOf((*MockServiceStorage)(nil).DeleteUsersFile), ctx, userID, fileID, fileName)
}

// DownloadFile mocks base method.
func (m *MockServiceStorage) DownloadFile(ctx context.Context, userID, fileID string) (*model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, userID, fileID)
	ret0, _ := ret[0].(*model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockServiceStorageMockRecorder) DownloadFile(ctx, userID, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockServiceStorage)(nil).DownloadFile), ctx, userID, fileID)
}

// GetUsersFiles mocks base method.
func (m *MockServiceStorage) GetUsersFiles(ctx context.Context, userID string) ([]*model.ExtendedInfoFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersFiles", ctx, userID)
	ret0, _ := ret[0].([]*model.ExtendedInfoFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersFiles indicates an expected call of GetUsersFiles.
func (mr *MockServiceStorageMockRecorder) GetUsersFiles(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersFiles", reflect.TypeOf((*MockServiceStorage)(nil).GetUsersFiles), ctx, userID)
}

// UploadFile mocks base method.
func (m *MockServiceStorage) UploadFile(ctx context.Context, file model.File, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, file, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockServiceStorageMockRecorder) UploadFile(ctx, file, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockServiceStorage)(nil).UploadFile), ctx, file, userID)
}

// UploadPlainText mocks base method.
func (m *MockServiceStorage) UploadPlainText(ctx context.Context, userID, content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPlainText", ctx, userID, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPlainText indicates an expected call of UploadPlainText.
func (mr *MockServiceStorageMockRecorder) UploadPlainText(ctx, userID, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPlainText", reflect.TypeOf((*MockServiceStorage)(nil).UploadPlainText), ctx, userID, content)
}
