// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mock is a generated GoMock package.
package mock

import (
	bytes "bytes"
	context "context"
	reflect "reflect"

	entity "github.com/Makovey/go-keeper/internal/repository/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockFileStorager is a mock of FileStorager interface.
type MockFileStorager struct {
	ctrl     *gomock.Controller
	recorder *MockFileStoragerMockRecorder
}

// MockFileStoragerMockRecorder is the mock recorder for MockFileStorager.
type MockFileStoragerMockRecorder struct {
	mock *MockFileStorager
}

// NewMockFileStorager creates a new mock instance.
func NewMockFileStorager(ctrl *gomock.Controller) *MockFileStorager {
	mock := &MockFileStorager{ctrl: ctrl}
	mock.recorder = &MockFileStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorager) EXPECT() *MockFileStoragerMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockFileStorager) Save(path, fileName string, data bytes.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", path, fileName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFileStoragerMockRecorder) Save(path, fileName, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFileStorager)(nil).Save), path, fileName, data)
}

// MockRepositoryStorage is a mock of RepositoryStorage interface.
type MockRepositoryStorage struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryStorageMockRecorder
}

// MockRepositoryStorageMockRecorder is the mock recorder for MockRepositoryStorage.
type MockRepositoryStorageMockRecorder struct {
	mock *MockRepositoryStorage
}

// NewMockRepositoryStorage creates a new mock instance.
func NewMockRepositoryStorage(ctrl *gomock.Controller) *MockRepositoryStorage {
	mock := &MockRepositoryStorage{ctrl: ctrl}
	mock.recorder = &MockRepositoryStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryStorage) EXPECT() *MockRepositoryStorageMockRecorder {
	return m.recorder
}

// SaveFileMetadata mocks base method.
func (m *MockRepositoryStorage) SaveFileMetadata(ctx context.Context, fileData *entity.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFileMetadata", ctx, fileData)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFileMetadata indicates an expected call of SaveFileMetadata.
func (mr *MockRepositoryStorageMockRecorder) SaveFileMetadata(ctx, fileData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFileMetadata", reflect.TypeOf((*MockRepositoryStorage)(nil).SaveFileMetadata), ctx, fileData)
}
