name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Run tests
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      # только для дебага и ревью
      - name: Copy .env to the build output directory
        run: |
          mkdir -p ./bin/
          cp .env ./bin/
          cd ./bin
          mv .env env
          cd ../

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o ./bin/keeper-windows.exe ./cmd/keeper

      - name: Build macOS
        run: GOOS=darwin GOARCH=amd64 go build -o ./bin/keeper-macos ./cmd/keeper

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o ./bin/keeper-linux ./cmd/keeper

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keeper-package
          path: ./bin/**

      - name: Rename Env
        run: |
          cd ./bin
          ls -a
          mv env .env
          ls -a