name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build binaries
    needs: test
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            ext: .exe
            suffix: windows
          - os: macos-latest
            ext:
            suffix: macos
          - os: ubuntu-latest
            ext:
            suffix: linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Build
        run: |
          GOOS=${{ matrix.suffix }} GOARCH=amd64 go build -o "keeper-${{ matrix.suffix }}${{ matrix.ext }}" ./cmd/keeper

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: keeper-${{ matrix.suffix }}
          path: keeper-${{ matrix.suffix }}${{ matrix.ext }}