name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Run tests
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o keeper-windows.exe ./cmd/keeper

      - name: Build macOS
        run: GOOS=darwin GOARCH=amd64 go build -o keeper-macos ./cmd/keeper

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o keeper-linux ./cmd/keeper

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: keeper-windows
          path: keeper-windows.exe

      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: keeper-macos
          path: keeper-macos

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: keeper-linux
          path: keeper-linux